language: node_js

notifications:
  email:
  - 228474838@qq.com
  - 1123978215@qq.com
  - celina520524@163.com

node_js:
    - 9.0.0
    - 9.5.0

env:
  matrix:
    - TEST_TYPE=build
    - TEST_TYPE=compile
    - TEST_TYPE=test

before_install:
  - npm -g install yarn

install:
  - npm install

script:
  - |
    if [ "$TEST_TYPE" = build ]; then
      npm run build
    elif [ "$TEST_TYPE" = compile ]; then
      npm run babel-cli
    elif [ "$TEST_TYPE" = test ]; then
      npm run test
    fi

branches:
  only:
  - develop_travis
